name: setup-stubcc
description: setup-stubcc downloads and installs mario-campos/stubcc as `gcc` and `clang`.
outputs:
  clang:
    description: "clang" installation path
    value: ${{ steps.install-clang.outputs.path }}
  gcc:
    description: "gcc" installation path
    value: ${{ steps.install-gcc.outputs.path }}
runs:
  using: composite
  steps:
    - shell: bash
      run: wget https://github.com/mario-campos/stubcc/releases/download/v0.1.0/stubcc-linux64
    - id: install-clang
      shell: bash
      run: |
        install -m 755 stubcc-linux64 "$RUNNER_TEMP/clang"
        echo "::set-output name=path::$RUNNER_TEMP/clang"
    - id: install-gcc
      shell: bash
      run: |
        install -m 755 stubcc-linux64 "$RUNNER_TEMP/gcc"
        echo "::set-output name=path::$RUNNER_TEMP/gcc"
